version: "3.3"
services:
  order:
      build: .
      image: order
      container_name: order
      restart: always
      ports:
       - "8007:8007"
       - "7011:7011"
      volumes:
       - /home/ubuntu/.aws:/root/.aws:ro                                               