version: "3.9"
services:
  order:
    build: .
      container-name: order
      restart: always
    ports:
      - "8007:8007"
      - "7011:7011"
      - "9091:9091"
    volumes:
      - /home/ubuntu/.aws:/root/.aws:ro