// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/swiggy-2022-bootcamp/cdp-team4/order/domain"
	errs "github.com/swiggy-2022-bootcamp/cdp-team4/order/utils/errs"

	mock "github.com/stretchr/testify/mock"
)

// OrderOverviewRepository is an autogenerated mock type for the OrderOverviewRepository type
type OrderOverviewRepository struct {
	mock.Mock
}

// GetOrderOverview provides a mock function with given fields: _a0
func (_m *OrderOverviewRepository) GetOrderOverview(_a0 string) (*domain.OrderOverview, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.OrderOverview
	if rf, ok := ret.Get(0).(func(string) *domain.OrderOverview); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OrderOverview)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// InsertOrderOverview provides a mock function with given fields: _a0
func (_m *OrderOverviewRepository) InsertOrderOverview(_a0 domain.OrderOverview) (bool, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(domain.OrderOverview) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(domain.OrderOverview) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}
