// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: reward.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRewardPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetRewardPointsRequest) Reset() {
	*x = GetRewardPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRewardPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRewardPointsRequest) ProtoMessage() {}

func (x *GetRewardPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRewardPointsRequest.ProtoReflect.Descriptor instead.
func (*GetRewardPointsRequest) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{0}
}

func (x *GetRewardPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRewardPointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardPoints uint32 `protobuf:"varint,1,opt,name=rewardPoints,proto3" json:"rewardPoints,omitempty"`
}

func (x *GetRewardPointsResponse) Reset() {
	*x = GetRewardPointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRewardPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRewardPointsResponse) ProtoMessage() {}

func (x *GetRewardPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRewardPointsResponse.ProtoReflect.Descriptor instead.
func (*GetRewardPointsResponse) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{1}
}

func (x *GetRewardPointsResponse) GetRewardPoints() uint32 {
	if x != nil {
		return x.RewardPoints
	}
	return 0
}

type UpdateRewardPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RewardPoints uint32 `protobuf:"varint,2,opt,name=rewardPoints,proto3" json:"rewardPoints,omitempty"`
}

func (x *UpdateRewardPointsRequest) Reset() {
	*x = UpdateRewardPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reward_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRewardPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRewardPointsRequest) ProtoMessage() {}

func (x *UpdateRewardPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRewardPointsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRewardPointsRequest) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRewardPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRewardPointsRequest) GetRewardPoints() uint32 {
	if x != nil {
		return x.RewardPoints
	}
	return 0
}

type UpdatePointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateResponse bool `protobuf:"varint,1,opt,name=updateResponse,proto3" json:"updateResponse,omitempty"`
}

func (x *UpdatePointsResponse) Reset() {
	*x = UpdatePointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reward_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointsResponse) ProtoMessage() {}

func (x *UpdatePointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePointsResponse) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePointsResponse) GetUpdateResponse() bool {
	if x != nil {
		return x.UpdateResponse
	}
	return false
}

var File_reward_proto protoreflect.FileDescriptor

var file_reward_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22,
	0x57, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9c, 0x01, 0x0a, 0x08, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reward_proto_rawDescOnce sync.Once
	file_reward_proto_rawDescData = file_reward_proto_rawDesc
)

func file_reward_proto_rawDescGZIP() []byte {
	file_reward_proto_rawDescOnce.Do(func() {
		file_reward_proto_rawDescData = protoimpl.X.CompressGZIP(file_reward_proto_rawDescData)
	})
	return file_reward_proto_rawDescData
}

var file_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reward_proto_goTypes = []interface{}{
	(*GetRewardPointsRequest)(nil),    // 0: GetRewardPointsRequest
	(*GetRewardPointsResponse)(nil),   // 1: GetRewardPointsResponse
	(*UpdateRewardPointsRequest)(nil), // 2: UpdateRewardPointsRequest
	(*UpdatePointsResponse)(nil),      // 3: UpdatePointsResponse
}
var file_reward_proto_depIdxs = []int32{
	0, // 0: Shipping.GetRewardPoints:input_type -> GetRewardPointsRequest
	2, // 1: Shipping.UpdateShippingAddress:input_type -> UpdateRewardPointsRequest
	1, // 2: Shipping.GetRewardPoints:output_type -> GetRewardPointsResponse
	3, // 3: Shipping.UpdateShippingAddress:output_type -> UpdatePointsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reward_proto_init() }
func file_reward_proto_init() {
	if File_reward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRewardPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRewardPointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reward_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRewardPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reward_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reward_proto_goTypes,
		DependencyIndexes: file_reward_proto_depIdxs,
		MessageInfos:      file_reward_proto_msgTypes,
	}.Build()
	File_reward_proto = out.File
	file_reward_proto_rawDesc = nil
	file_reward_proto_goTypes = nil
	file_reward_proto_depIdxs = nil
}
