// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/swiggy-2022-bootcamp/cdp-team4/shipping/domain"
	errs "github.com/swiggy-2022-bootcamp/cdp-team4/shipping/utils/errs"

	mock "github.com/stretchr/testify/mock"
)

// ShippingAddressRepository is an autogenerated mock type for the ShippingAddressRepository type
type ShippingAddressRepository struct {
	mock.Mock
}

// DeleteShippingAddressById provides a mock function with given fields: _a0
func (_m *ShippingAddressRepository) DeleteShippingAddressById(_a0 string) (bool, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// FindShippingAddressById provides a mock function with given fields: _a0
func (_m *ShippingAddressRepository) FindShippingAddressById(_a0 string) (*domain.ShippingAddress, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.ShippingAddress
	if rf, ok := ret.Get(0).(func(string) *domain.ShippingAddress); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShippingAddress)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// InsertShippingAddress provides a mock function with given fields: _a0
func (_m *ShippingAddressRepository) InsertShippingAddress(_a0 domain.ShippingAddress) (string, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.ShippingAddress) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(domain.ShippingAddress) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// UpdateShippingAddressById provides a mock function with given fields: _a0, _a1
func (_m *ShippingAddressRepository) UpdateShippingAddressById(_a0 string, _a1 domain.ShippingAddress) (bool, *errs.AppError) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, domain.ShippingAddress) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string, domain.ShippingAddress) *errs.AppError); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}
