GET http://localhost:7001/order/user/482b7e39-da41-461d-8676-cee6bf3654f7


###

POST http://localhost:7001/order
content-type: application/json

{
    "user_id":"482b7e39-da41-461d-8676-cee6bf3654f7",
    "status":"confirmed",
    "products": [
        {
        "name":"Theory of Everything",
        "cost": 350,
        "quantity":1
        },
        {
        "name":"Parker",
        "cost":  100,
        "quantity":4
        }
    ],
    "total_cost":800
}

###

GET http://localhost:7001/order/98fd218a-3544-45d1-8d50-e2ef8cc1e4e9


###

GET http://localhost:7001/orders


###
GET http://localhost:7001/order/status/confirmed

####
PUT http://localhost:7001/order/status
Content-Type: application/json

{
    "id":"98fd218a-3544-45d1-8d50-e2ef8cc1e4e9",
    "status":"declined"
}

####
DELETE http://localhost:7001/order/79d97b2c-6dd7-4a75-893a-f958e2f82a91

