GET http://localhost:8007/order/user/482b7e39-da41-461d-8676-cee6bf3654f7


###

POST http://localhost:8007/order
content-type: application/json

{
    "user_id":"482b7e39-da41-461d-8676-cee6bf3654f7",
    "status":"confirmed",
    "products": [
        {
        "name":"Da Vinci Code",
        "cost": 699,
        "quantity":1
        },
        {
        "name":"Parker",
        "cost":  100,
        "quantity":4
        }
    ],
    "total_cost":1200
}

###

GET http://localhost:8007/order/fc2e08ca-1e6f-4e10-bedb-8c5e4ff3a98d


###

GET http://localhost:8007/orders/


###
GET http://localhost:8007/order/status/confirmed

####
PUT http://localhost:8007/order/status
Content-Type: application/json

{
    "id":"b072ad81-2d45-43e0-b4a9-5a376aba9e08",
    "status":"pending"
}

####
DELETE http://localhost:8007/order/b072ad81-2d45-43e0-b4a9-5a376aba9e08

####
POST http://localhost:8007/confirm/1576570

