GET http://localhost:8007/order/user/482b7e39-da41-461d-8676-cee6bf3654f7


###

POST http://54.86.110.234:8007/order
content-type: application/json

{
    "user_id":"482b7e39-da41-461d-8676-cee6bf3654f7",
    "status":"confirmed",
    "products": [
        {
        "name":"Da Vinci Code",
        "cost": 699,
        "quantity":1
        },
        {
        "name":"Parker",
        "cost":  100,
        "quantity":4
        }
    ],
    "total_cost":1200
}

###

GET http://54.86.110.234:8007/order/82f049a4-ff9d-4fd1-a6a5-d76431824a5f

###

GET http://54.86.110.234:8007/orders/


###
GET http://localhost:8007/order/status/confirmed

####
PUT http://localhost:8007/order/status
Content-Type: application/json

{
    "id":"81e5c913-cb74-4d62-a4da-412cc740a506",
    "status":"pending"
}

####
DELETE http://localhost:8007/order/81e5c913-cb74-4d62-a4da-412cc740a506

####
POST http://localhost:8007/confirm/b533ab38-97f4-4c43-a891-c43872d9f15a

####
GET http://localhost:8007/order/invoice/72d56385-d08a-4f51-ac71-3354734e371c

