// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\DELL\Desktop\final_project_S\cdp-team4\user\app\userHandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	app "github.com/swiggy-2022-bootcamp/cdp-team4/user/app"
)

// MockGrpcHelper is a mock of GrpcHelper interface.
type MockGrpcHelper struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcHelperMockRecorder
}

// MockGrpcHelperMockRecorder is the mock recorder for MockGrpcHelper.
type MockGrpcHelperMockRecorder struct {
	mock *MockGrpcHelper
}

// NewMockGrpcHelper creates a new mock instance.
func NewMockGrpcHelper(ctrl *gomock.Controller) *MockGrpcHelper {
	mock := &MockGrpcHelper{ctrl: ctrl}
	mock.recorder = &MockGrpcHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcHelper) EXPECT() *MockGrpcHelperMockRecorder {
	return m.recorder
}

// GetShippingAddressId mocks base method.
func (m *MockGrpcHelper) GetShippingAddressId(arg0 app.ShippingAddressDTO) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShippingAddressId", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetShippingAddressId indicates an expected call of GetShippingAddressId.
func (mr *MockGrpcHelperMockRecorder) GetShippingAddressId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShippingAddressId", reflect.TypeOf((*MockGrpcHelper)(nil).GetShippingAddressId), arg0)
}
