version: "3.3"
services:
  order:
      build: .
      image: checkout
      container_name: checkout
      restart: always
      ports:
       - "8011:8011"
       - "7011:7011"
      volumes:
       - /home/ubuntu/.aws:/root/.aws:ro       
