version: "3.3"
services:
  order:
      build: .
      image: category
      container_name: category
      restart: always
      ports:
       - "8005:8005"
      volumes:
       - /home/ubuntu/.aws:/root/.aws:ro                                               