basePath: /
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Category Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: category Service
  version: "1.0"
paths:
  /:
    get:
      description: this api is used to check whether category service is up and running
        or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Health of category service
      tags:
      - Health
  /categories/:
    delete:
      description: This Handle allows admin to delete categories, given Ids
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Delete Categories details
      tags:
      - Category
    get:
      description: This Handle allows admin to fetch all the categories in the datastore
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Get all Categories
      tags:
      - Categories
    post:
      description: This Handle allows admin to create a new category
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Add Category
      tags:
      - Category
  /categories/:id:
    delete:
      description: This Handle allows admin to delete a category, given Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Delete Category details by Id
      tags:
      - Category
    get:
      description: This Handle allows admin to get a category, given Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Get Category details by Id
      tags:
      - Category
    put:
      description: This Handle allows admin to update a category, given Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Update Category details by Id
      tags:
      - Category
swagger: "2.0"
