# Get Orders

# curl -H "X-API-Key: e0aaf890" https://my.api.mockaroo.com/orders
GET https://my.api.mockaroo.com/orders
X-API-Key: e0aaf890

###

# Get Orders by id

# curl -H "X-API-Key: e0aaf890" https://my.api.mockaroo.com/orders/123
GET https://my.api.mockaroo.com/orders/123
X-API-Key: e0aaf890

###

# Get Orders by user id

# curl -H "X-API-Key: e0aaf890" https://my.api.mockaroo.com/orders/user/123
GET https://my.api.mockaroo.com/orders/user/123
X-API-Key: e0aaf890

###

# Get Orders by status

# curl -H "X-API-Key: e0aaf890" https://my.api.mockaroo.com/orders/status/confirmed
GET https://my.api.mockaroo.com/orders/status/confirmed
X-API-Key: e0aaf890

###

# Get Invoice given order id

# curl -H "X-API-Key: e0aaf890" https://my.api.mockaroo.com/orders/invoice/123
GET https://my.api.mockaroo.com/orders/invoice/123
X-API-Key: e0aaf890

###

# Update order by order id

# curl -H "X-API-Key: e0aaf890" -X PUT https://my.api.mockaroo.com/orders/123

PUT https://my.api.mockaroo.com/orders/123
X-API-Key: e0aaf890

###

# Delete order by order id

# curl -H "X-API-Key: e0aaf890" -X DELETE https://my.api.mockaroo.com/orders/123

DELETE https://my.api.mockaroo.com/orders/123
X-API-Key: e0aaf890
