POST http://localhost:8012/shippingaddress
Content-Type: application/json

{
 "firstname": "Vineet",
 "lastname": "Kumar",
 "city": "Bengaluru",
 "address_1": "Demo",
 "address_2": "Demo",
 "country_id": 86,
 "postcode": 590068
}


###

GET http://localhost:8012/shippingaddress/9b718e72-ca0a-410c-a817-97b1bbef416d
###

PUT http://localhost:8012/shippingaddress/9b718e72-ca0a-410c-a817-97b1bbef416d

{
 "firstname": "Vineet",
 "lastname": "Kumar",
 "city": "Bengaluru",
 "address_1": "Demo",
 "address_2": "Demo",
 "country_id": 69,
 "postcode": 567893
}

###

DELETE http://localhost:8012/shippingaddress/2ae72080-59f8-43b9-b514-af0ea970c242


###

POST http://localhost:8012/shippingcost
Content-Type: application/json

{
 "city":"Mumbai",
 "cost":777
}

###
GET http://localhost:8012/shippingcost/Mumbai

###
PUT http://localhost:8012/shippingcost
Content-Type: application/json

{
 "city":"Mumbai",
 "cost":7899
}

###
DELETE  http://localhost:8012/shippingcost/Mumbai
